# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d29ac5cbd9a41ae896534f26be8b7d39785e7fa09b4d1ff97f858be5d238b9191287f3afc9464e27a13619c56a1d5d06287485677b2cb622521ceffb87fc1129

test:
  secret_key_base: 554617d43b1440836ecfa9087f62d483702fedf3c3687e083eed6dd9795c2d83364743ac11be6b16f5a79f39df04893aa916414e5064f12837853350d9b7b324

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
